#%RAML 1.0 Trait
 headers:
  x-fms-transactionId:
    required: true
    maxLength: 36
    minLength: 36
    type: string
    example: "1234568790-nafasfdskvkdsvkd-3452-oei"
  x-fms-clientId:
    required: true
    type: string
    example: "456398akahaie45"  
  x-fms-clientSecret:
    required: true 
    type: string
    example: "43ahak54haalfdfs"
          